services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Subugoe\IIIFBundle\Service\ImageService:
    arguments:  ["@liip_imagine", "@router", "@subugoe_iiif.translator",'@Subugoe\IIIFBundle\Service\FileService']
    calls:
      - method: 'setImageConfiguration'
        arguments:
          - '%image%'

  Subugoe\IIIFBundle\Service\FileService:

  Subugoe\IIIFBundle\Service\PresentationService:
    arguments:  ["@router", "%image%", "%presentation%"]

  #
  # The following definition is an example on how to create the translator
  #
  #Subugoe\IIIFBundle\Translator\TranslatorInterface:
  #  class:      Subugoe\IIIFBundle\Translator\SubugoeTranslator
  #  arguments:  ["@subugoe_find.search_service", "@router"]
