services:
  Subugoe\IIIFBundle\Service\ImageService:
    arguments:  ["@liip_imagine", "@router", "@subugoe_iiif.translator",'@Subugoe\IIIFBundle\Service\FileService']
    calls:
      - method: 'setImageConfiguration'
        arguments:
          - '%image%'

  Subugoe\IIIFBundle\Service\FileService:
    arguments:  ["@cache_filesystem", "@source_filesystem"]

  Subugoe\IIIFBundle\Service\PresentationService:
    arguments:  ["@router", "%image%", "%presentation%"]

  Subugoe\IIIFBundle\EventListener\UrlManipulatorListener:
      arguments: ['%image%', '%presentation%', '@router']
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  #
  # The following definition is an example on how to create the translator
  #
  #Subugoe\IIIFBundle\Translator\TranslatorInterface:
  #  class:      Subugoe\IIIFBundle\Translator\SubugoeTranslator
  #  arguments:  ["@subugoe_find.search_service", "@router"]
